/*
DROP DATABASE IF EXISTS booklibrary

CREATE DATABASE booklibrary;

CREATE USER me
WITH ENCRYPTED PASSWORD 'x';


\c newarrival; 
*/
DROP TABLE IF EXISTS newarrival;

CREATE TABLE newarrival(
    id numeric null,
    title text null,
    author text null,
    year varchar null,
    publisher text null,
    synopsis text null,
    coverimg text null
);

INSERT INTO newarrival (id,title,author,"year",publisher,synopsis,coverimg) VALUES 
(102,'Indianapolis: The True Story of the Worst Sea Disaster in U.S. Naval History and the Fifty-Year Fight to Exonerate an Innocent Man','Lynn Vincent, Sara Vladic','2018','Simon and Schuster','As anyone who''s ever watched Jaws remembers, many of the Indianapolis''s sailors were eaten by sharks in the four days before they were discovered adrift in the Pacific during World War II. While the horrifying shark scenes will spark many readers to pick up the book, the rest of the Indianapolis''s story is equally as tense, from its top-secret mission to deliver materials for the first atomic bomb dropped on Japan, to the sailors'' frantic attempts to get out a distress call after they were torpedoed at night, to the court-martial of the captain—a court-martial that his crew fought against even after McVay''s suicide.','https://images-na.ssl-images-amazon.com/images/I/81EOTq-nUaL._AC_SR201,266_.jpg')
,(103,'Elevation','Stephen King','2018','Scribner','When we first meet Scott Carey, he is knocking on the door of a doctor’s condo. Carey discloses to the doctor that he is experiencing a unique condition: he is losing weight but not mass. Every day he is a little lighter and no one can tell the difference. When the doctor points out that this is likely not a condition treatable by modern medicine, Carey appears to concur. So if he is possibly running out of time, what’s next? ','https://images-na.ssl-images-amazon.com/images/I/71tXuzNDDmL._AC_SR201,266_.jpg')
,(100,'Educated: A Memoir','Tara Westover','2018','Random House','Tara Westover wasn’t your garden variety college student. When the Holocaust was mentioned in a history class, she didn’t know what it was (no, really). That’s because she didn’t see the inside of a classroom until the age of seventeen. Public education was one of the many things her religious fanatic father was dubious of, believing it a means for the government to brainwash its gullible citizens, and her mother wasn’t diligent on the homeschooling front. If it wasn’t for a brother who managed to extricate himself from their isolated—and often dangerous--world, Westover might still be in rural Idaho, trying to survive her survivalist upbringing. It’s a miraculous story she tells in her memoir Educated. For those of us who took our educations for granted, who occasionally fell asleep in large lecture halls (and inconveniently small ones), it’s hard to grasp the level of grit—not to mention intellect—required to pull off what Westover did. But eventually earning a PhD from Cambridge University may have been the easy part, at least compared to what she had to sacrifice to attain it. The courage it took to make that sacrifice was the truest indicator of how far she’d come, and how much she’d learned. Educated is an inspiring reminder that knowledge is, indeed, power ','https://images-na.ssl-images-amazon.com/images/I/81WojUxbbFL._AC_SR201,266_.jpg')
,(101,'Washington Black: A novel ','Esi Edugyan','2018','Knopf','The story begins as an antebellum novel about Wash, an 11-year-old slave working on a Barbados plantation run by a sadistic master. When Christopher, the master’s brother, takes Wash under his wing and teaches him to read, the novel turns more toward adventure and scientific exploration. There are inventions, twists, and turns; there is danger and intrigue; there is travel and growth. ','https://images-na.ssl-images-amazon.com/images/I/8192PLY5ggL._AC_SR201,266_.jpg')
,(104,'The Line Becomes a River: Dispatches from the Border','Francisco Cantú','2018','Riverhead Books','These days, mention of “the Border” stirs both imagination and emotion, what you see and feel depending on how you perceive the world. But how many of us understand this real-world interzone where actual borders shift and bleed, and hard scenes of death, drug smuggling, and human suffering unfold daily? The son of a park ranger, Francisco Cantú grew up in the southwest. When he joined the Border Patrol, he became witness to the stark realities of the desert, where the obligations of his job weighed heavy against his sense of humanity. Dark material for sure, but Cantú is a good no-nonsense writer, and his direct, stoic prose makes The Line Becomes a River a weighty and timely document on one of our most divisive arguments','https://images-na.ssl-images-amazon.com/images/I/81SNfjMBWJL._AC_SR201,266_.jpg')
,(107,'Children of Blood and Bone (Legacy of Orisha)','Tomi Adeyemi','2018','Henry Holt and Co.','The Children of Blood and Bone is told from multiple points of view, as Inan and Amari, children of the iron-fisted king, and Zélie and Tzain, siblings who have suffered greatly under the king’s regime, find themselves on a dark, magic-filled quest for power. Their journey is accompanied by violence and betrayal, but friendship and even star-crossed love also play a part. Enriched with themes that resonate in today’s social and political landscape, The Children of Blood and Bone takes on injustice, discrimination, and a struggle for change.','https://images-na.ssl-images-amazon.com/images/I/A1agLFsWkOL._AC_SR201,266_.jpg')
,(108,'Virgil Wander','Leif Enger','2018','Grove Press','It’s an endearing yarn, set in a sleepy town near Lake Superior, inhabited by a quirky cast of characters (and even quirkier raccoon and sturgeon). But you quickly discover that all is not quiet on the Midwestern front: The town is in decline; the novel’s namesake has just been in a harrowing car crash; an enigmatic kite enthusiast arrives, searching for his missing son; and, unbeknownst to all, a heartbroken handyman has embarked on a sinister project','https://images-na.ssl-images-amazon.com/images/I/91mHEJDPV-L._AC_SR201,266_.jpg')
,(110,'The Great Alone: A Novel','Kristin Hannah','2018','St. Martin''s Press','A damaged vet named Ernt Allbright returns from Vietnam and moves his family to the wilds of Alaska to start their lives anew. Initially it''s a welcome change, but as winter approaches, and Ernt''s mental state deteriorates, his wife and daughter find themselves in an increasingly precarious position','https://images-na.ssl-images-amazon.com/images/I/511Dl74cE9L._AC_SR201,266_.jpg')
,(111,'Dopesick: Dealers, Doctors, and the Drug Company that Addicted America','Beth Macy','2018','Little, Brown, and Company','Beth Macy’s book revealed the greed that drove OxyContin to be America’s drug of choice, and it opened my eyes to the shame of addiction that kept this epidemic hidden until far too late. Opioid addiction has touched nearly all of us in the 20 years since OxyContin came to market, and it’s something that didn’t have to happen. Money--absurdly huge sums of it--encouraged doctors, politicians, and the pharmaceutical industry to accept claims about the safety of this painkiller even when it was in conflict with what they saw in their practices and communities','https://images-na.ssl-images-amazon.com/images/I/51btuIO7E2L._AC_SR201,266_.jpg')
,(113,'My Year of Rest and Relaxation','Ottessa Moshfegh','2018','Penguin Press','My Year of Rest and Relaxation takes place in 2001, when a pretty young Columbia graduate with an easy job at an art gallery decides to take a year off just to sleep. She has access to a quack psychiatrist willing to prescribe her an arsenal of pills, and she has money that she inherited from her deceased parents. She also has a terrible older boyfriend who works on Wall Street and a best friend, Reva, with whom she shares a thorny, complicated relationship.','https://images-na.ssl-images-amazon.com/images/I/513uyAYdssL._AC_SR201,266_.jpg')
;

INSERT INTO newarrival (id,title,author,"year",publisher,synopsis,coverimg) VALUES 
(114,'Frederick Douglass: Prophet of Freedom ','David W. Blight','2018','Simon and Schuster','As a young man Frederick Douglass (1818–1895) escaped from slavery in Baltimore, Maryland. He was fortunate to have been taught to read by his slave owner mistress, and he would go on to become one of the major literary figures of his time. He wrote three versions of his autobiography over the course of his lifetime and published his own newspaper. His very existence gave the lie to slave owners: with dignity and great intelligence he bore witness to the brutality of slavery','https://images-na.ssl-images-amazon.com/images/I/810ygjggs-L._AC_SR201,266_.jpg')
,(115,'21 Lessons for the 21st Century ','Yuval Noah Harari','2018','Spiegel and Grau','How do computers and robots change the meaning of being human? How do we deal with the epidemic of fake news? Are nations and religions still relevant? What should we teach our children? Yuval Noah Harari’s 21 Lessons for the 21st Century is a probing and visionary investigation into today’s most urgent issues as we move into the uncharted territory of the future. As technology advances faster than our understanding of it, hacking becomes a tactic of war, and the world feels more polarized than ever, Harari addresses the challenge of navigating life in the face of constant and disorienting change and raises the important questions we need to ask ourselves in order to survive.','https://images-na.ssl-images-amazon.com/images/I/81o9vblSjmL._AC_SR201,266_.jpg')
,(116,'The Witch Elm: A Novel','Tana French','2018','Viking','Toby is a happy-go-lucky charmer who''s dodged a scrape at work and is celebrating with friends when the night takes a turn that will change his life - he surprises two burglars who beat him and leave him for dead. Struggling to recover from his injuries, beginning to understand that he might never be the same man again, he takes refuge at his family''s ancestral home to care for his dying uncle Hugo. Then a skull is found in the trunk of an elm tree in the garden - and as detectives close in, Toby is forced to face the possibility that his past may not be what he has always believed.','https://images-na.ssl-images-amazon.com/images/I/A1MJ4CJOigL._AC_SR201,266_.jpg')
,(106,'Once Upon a River: A Novel','Diane Setterfield','2018','Atria/Emily Bestler Books','When a man bursts into a riverside inn on the longest night of the year, covered in blood and carrying a dead child, the patrons of the Swan are beyond thrilled to find themselves in the middle of a swiftly unfolding tale—especially when the child is determined to actually be alive. Is the mute girl the long-missing daughter of a nearby wealthy family, or the bastard child of woman who threw herself in the Thames only a day or so earlier?','https://images-na.ssl-images-amazon.com/images/I/81l5GH15D%2BL._AC_SR201,266_.jpg')
,(105,'The Woman in the Window: A Novel ','AJ Finn','2018','William Morrow','The Woman in the Window is a seductive and unpredictable novel, like the Hitchcock movies to which author A.J. Finn pays homage. Finn’s protagonist Anna Fox is a child psychologist who lives alone in a New York suburb with a case of agoraphobia so debilitating she hasn’t left the house in months. To occupy her time Anna watches film noir classics from her vast collection, interacts with people online, and sometimes spies on her neighbors. It’s all very innocuous until she sees a horrible crime take place in the house across the park, recently inhabited by a new family','https://images-na.ssl-images-amazon.com/images/I/91wr7Rq7ZaL._AC_SR201,266_.jpg')
,(117,'Girls Burn Brighter: A Novel','Shoba Rao','2018','Flatiron books','Poornima and Savitha have three strikes against them: they are poor, they are ambitious, and they are girls. After her mother’s death, Poornima has very little kindness in her life. She is left to care for her siblings until her father can find her a suitable match. So when Savitha enters their household, Poornima is intrigued by the joyful, independent-minded girl. Suddenly their Indian village doesn''t feel quite so claustrophobic, and Poornima begins to imagine a life beyond arranged marriage. But when a devastating act of cruelty drives Savitha away, Poornima leaves behind everything she has ever known to find her friend. ','https://images-na.ssl-images-amazon.com/images/I/51a4LsvOXSL._AC_SR201,266_.jpg')
,(118,'The Tattooist of Auschwitz: A Novel ','Heather Morris','2018','Harper Paperbacks','In April 1942, Lale Sokolov, a Slovakian Jew, is forcibly transported to the concentration camps at Auschwitz-Birkenau. When his captors discover that he speaks several languages, he is put to work as a Tätowierer (the German word for tattooist), tasked with permanently marking his fellow prisoners. Imprisoned for over two and a half years, Lale witnesses horrific atrocities and barbarism—but also incredible acts of bravery and compassion. Risking his own life, he uses his privileged position to exchange jewels and money from murdered Jews for food to keep his fellow prisoners alive. One day in July 1942, Lale, prisoner 32407, comforts a trembling young woman waiting in line to have the number 34902 tattooed onto her arm. Her name is Gita, and in that first encounter, Lale vows to somehow survive the camp and marry her.','https://images-na.ssl-images-amazon.com/images/I/81XAhkfzn-L._AC_SR201,266_.jpg')
,(119,'Bad Blood: Secrets and Lies in a Silicon Valley Startup','John Carreyrou','2018','Knopf','In 2014, Theranos founder and CEO Elizabeth Holmes was widely seen as the female Steve Jobs: a brilliant Stanford dropout whose startup “unicorn” promised to revolutionize the medical industry with a machine that would make blood testing significantly faster and easier. Backed by investors such as Larry Ellison and Tim Draper, Theranos sold shares in a fundraising round that valued the company at more than $9 billion, putting Holmes’s worth at an estimated $4.7 billion. There was just one problem: The technology didn’t work.','https://images-na.ssl-images-amazon.com/images/I/71rtQvf5UVL._AC_SR201,266_.jpg')
,(109,'There There: A novel ','Tommy Orange','2018','Knopf','What does it really mean to be an Indian/Native American/American Indian/Native? Orange''s vivid debut novel allows a unique cast—ranging from teenagers to elders—to pull this question apart even as they add a modern layer of complexity: They live in the urban landscape of Oakland, California. The thrust of Orange''s cross-cut storytelling is not to force his characters onto a strict plot line but to explore the varied ways of being an Indian and, more important, of feeling like an Indian. Fractured families, Oakland itself, and detachment from tradition make an Indian identity seem even more elusive to the younger characters, but it''s a feeling that they unknowingly share—and that Orange wants to expose. ','https://images-na.ssl-images-amazon.com/images/I/81FHAZWBpeL._AC_SR201,266_.jpg')
,(112,'Wolves of Eden: A Novel ','Kevin McCarthy','2018','W. W. Norton and Company','The setting is post-Civil War in the Dakota Territory, where the U.S. Army has established forts and its soldiers’ time is mostly spent fighting the Native Americans whose land they keep poaching. McCarthy’s characters come alive on the page, particularly his narrators: the long-suffering and quite clever Corporal Daniel Kohn, and Irish immigrant Michael O’Driscoll who, along with his brother Thomas, re-joined the army when they ran out of options. After a politically connected brothel owner and his wife are murdered outside Fort Phil Kearney, Corporal Kohn, along with his superior, a drunk Lieutenant named Molloy, are sent to find the killer—or at least “a neck for the noose” to appease their bosses in Washington.','https://images-na.ssl-images-amazon.com/images/I/81O8doEYnqL._AC_SR201,266_.jpg')
;

/*
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON DATABASE portal TO postgres;
*/